# Generated by Django 5.2.13 on 2026-05-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_alpha', '0003_booking_user_alter_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
    ]
