# Generated by Django 5.2.13 on 2026-08-07 08:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_alpha', '0005_alter_hotel_options_booking_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRateLimit',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
